services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    restart: always
    hostname: '192.168.2.9.93'
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://192.168.2.93:40001'"
      - GITLAB_ROOT_EMAIL="admin@local"
      - GITLAB_ROOT_PASSWORD="admin123"
    ports:
      - '40001:80'
      - '40002:443'
      - '40000:22'
    volumes:
      - './Gitlab/config:/etc/gitlab'
      - './Gitlab/logs:/var/log/gitlab'
      - './Gitlab/data:/var/opt/gitlab'