services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    restart: always
    hostname: '192.168.2.93'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '192.168.2.93:40001'
        gitlab_rails['gitlab_shell_ssh_port'] = 40000
    ports:
      - '40001:80'
      - '40002:443'
      - '40000:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'